name: Build Mac
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Haxe
        uses: haxe-commons/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install Dependencies & Update Lime Submodules
        run: |
          haxelib install hxpkg
          haxelib run hxpkg setup
          haxelib run hxpkg install
          
          cd .haxelib/lime/git/
          git submodule sync --recursive
          git submodule update --init --recursive --force
          cd ../../../
          
          haxelib run lime rebuild cpp -release

      - name: Build Game for Mac
        run: |
          haxelib run lime build mac -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImpostorLegacy-Mac
          path: export/release/macos/bin/
